HotelAdvisor/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HotelAdvisor.Models
{
    public class Hotel
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage="Please, enter the name")]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required]
        public string Address { get; set; }

        [Display(Name="House number")]
        public int HouseNumber { get; set; }

        public string City { get; set; }

        public string Image { get; set; }

        [Display(Name="Is active")]
        public bool IsActive { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

    }
}

HotelAdvisor/Controllers/HotelController.cs
using HotelAdvisor.Managers;
using HotelAdvisor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelAdvisor.Controllers
{
    public class HotelController : Controller
    {
        // GET: Hotel

        public ActionResult Index()
        {
            HotelAdvisorContext context = new HotelAdvisorContext();
            var model = context.Hotels.ToList();

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Hotel model)
        {
            if(ModelState.IsValid)
            {
                HotelManager manager = new HotelManager();
                manager.Create(model);

                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

HotelAdvisor/Views/Hotel/Create.cshtml
@model HotelAdvisor.Models.Hotel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div>
    
    @using(Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
         <div>   
             @Html.ValidationSummary(true)
            <div>
                @Html.LabelFor(model=>model.Name)
                <div>
                    @Html.EditorFor(model=>model.Name)
                    @Html.ValidationMessageFor(model=>model.Name)
                </div>
            </div>
            <div>
                @Html.LabelFor(model => model.Description)
                <div>
                    @*@Html.TextAreaFor(model => model.Description, 2, 40, null)*@
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>
            <div>
                @Html.LabelFor(model => model.HouseNumber)
                <div>
                    @Html.EditorFor(model => model.HouseNumber)
                    @Html.ValidationMessageFor(model => model.HouseNumber)
                </div>
            </div>
            <div>
                @Html.LabelFor(model => model.IsActive)
                <div>
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive)
                </div>
            </div>

            <div>
                <input type="submit" value="Create"/>
            </div>
         </div>
    }

</div>

HotelAdvisor/Views/Hotel/Index.cshtml
@using System.Globalization;
@model IEnumerable<HotelAdvisor.Models.Hotel>

@{
    ViewBag.Title = "Index";
}

<div class="col-md-12">
    <div>
       <input type="button" value="Create" title="Create" onclick="location.href='@Url.Action("Create")'">
    </div>
    @foreach (var hotel in Model)
    {
        <div class="row top-buffer">
            <div class="col-md-3">
                <img src="@hotel.Image" alt="Hotel Image" width="200px" height="150px" />
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-3">
                        <h3>@Html.ActionLink(@hotel.Name, "Details", new { id = hotel.Id }) </h3>
                    </div>
                    @if (User.IsInRole("Admin"))
                    {
                        <div class="col-md-3" style="padding-top:20px">
                            <button class="btn btn-default btn-xs" type="button" title="Edit hotel" onclick="location.href='@Url.Action("Edit", "Hotel", new { id=hotel.Id})'">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </button>
                        </div>
                    }
                </div>
                <div>@hotel.Address @hotel.HouseNumber @hotel.City</div>
                <div>@hotel.Description</div>
            </div>
        </div>
    }
</div>